#!/bin/bash

script_name=$(basename $0)

function usage() {
    local e="$@"
    if [ -n "$e" ]; then
	echo 
	echo Error: $@ >&2
	echo
    fi
    echo "usage: " >&2
    echo "  $script_name <kernel-tree-path> <version-tag> -- [genkernel options]" >&2
    echo "  <version-tag> can be set to 'latest' to use the most recent tag" >&2
    echo "example:"
    echo "  $script_name ../linux.git latest -- --unionfs all::" >&2
    exit 1
}

which git-checkout &>/dev/null || usage "Could not find Git tools in your path"
which genkernel &>/dev/null || usage "Could not find 'genkernel' in your path"
[ "$#" -lt "3" ] && usage
[ "$3" != "--" ] && usage
ktree="$1"
ktag="$2"
[ ! -d "$ktree/.git" ] && usage "The path specified for the kernel tree is not a Git directory."
cd "$ktree"
if [ "$ktag" != "latest" ]; then
    [ "$(git-tag -l ^$ktag\$)" != "$ktag" ] && usage "The specified tag does not exist in the kernel git tree"
else
    echo -n "Finding the latest commit... "
    ktag=$( for i in `git-rev-parse --tags`; do git-log --pretty=format:"%ct %H" -1 $i; echo ; done | sort | cut -f2 -d' ' | tail -n1 )
    ktag=$( git-describe "$ktag" )
    echo $ktag
fi

echo "Checking out tag '$ktag' in the kernel tree"
git-checkout "$ktag" || exit 1


shift
shift
shift
# phew. alright now!

echo "Running genkernel $@ --kernel-tree='$ktree'"
echo
echo
genkernel $@ --kernel-tree="$ktree"
