#!/bin/sh
# Copyright 2006 Eric Edgar <rocket@gentoo.org>, 
#                Tim Yamin <plasmaroo@gentoo.org> and
#                Jean-Francois Richard <jean-francois@richard.name>
# Distributed under the terms of the GNU General Public License v2
#
#
# Block device root fs loader for genkernel
#
# ./block --do-mount mountpoint device mount_opts
#

. /etc/initrd.defaults
. "${LIBGMI}/libgmi.sh"

### TODO: Untested


parameters() {
        echo 'device mount_opts'
}


help() {
cat << EOHELP
usage: block:<device>[:mount_opts]
example: 'root=block:/dev/hda2'
         'root=block:/dev/hda2:ro,noatime'
parameters are
<device>       device containing the filesystem
[mount_opts]   parameters to pass at mounting of the filesystem
EOHELP
}


do_mount() {
	# unwrapping parameters for human beings
	local mountpoint="${1}"
	local device="${2}"
	local mount_opts="${3}"
	local _mount_opts

	is_set ${mount_opts} && _mount_opts="-o ${mount_opts}"

	dbg_msg "mount ${_mount_opts} ${device} ${mountpoint}"
	mount ${_mount_opts} ${device} ${mountpoint}
	assert "$?" "Could not mount block device '${device}'" || return 1
}


case "${1}" in
	"--help")
		help
		;;
	"--parameters")
		parameters
		;;
	"--do-mount")
		shift
		do_mount $@
		exit $?
		;;
	*)
		exit 1
		;;
esac
